@startuml

title "山海经-第三层"

skinparam packageStyle rectangle

rectangle 中山经 {
    (中山薄山)-down->(中次二山济山)
    (中次二山济山)-down->(中次三山负山)
    (中次三山负山)-down->(中次四山厘山)
    (中次四山厘山)-down->(中次五山薄山)
    (中次五山薄山)-down->(中次六山缟羝山)
    (中次六山缟羝山)-down->(中次七山苦山)
    (中次七山苦山)-down->(中次八山荆山)
    (中次八山荆山)-down->(中次九山岷山)
    (中次九山岷山)-down->(中次十山)
    (中次十山)-down->(中次一十一山荆山)
    (中次一十一山荆山)-down->(中次十二山洞庭山)
}

rectangle 东山经 {
    (东山之首)-right->(东次二山)
    (东次二山)-right->(东次三山)
    (东次三山)-right->(东次四山)
}

rectangle 北山经 {
    (北山之首)-up->(北次二山)
    (北次二山)-up->(北次三山)
}

rectangle 西山经 {
    rectangle 西山华山 {
        (钱来山)-left->(松果山):西四十五里
        (松果山)-left->(太华山):西六十里
        (太华山)-left->(小华山):西八十里
        (小华山)-left->(符禺山):西八十里
        (符禺山)-left->(石脆山):西六十里
        (石脆山)-left->(英山):西七十里
        (英山)-left->(竹山):西五十二里
        (竹山)-left->(浮山):西一百二十里
        (浮山)-left->(羭次山):西七十里
        (羭次山)-left->(时山):西一百五十里
        (时山)-left->(南山):西一百七十里
        (南山)-left->(大时山):西一百八十里
        (大时山)-left->(嶓冢山):西三百二十里
        (嶓冢山)-left->(天帝山):西三百五十里
        (天帝山)-left->(皋涂山):西南三百八十里
        (皋涂山)-left->(黄山):西一百八十里
        (黄山)-left->(翠山):西二百里
        (翠山)-left->(螝山):西二百五十里
    }

    rectangle 西次二山 {
        (铃山)-left->(泰冒山):西二百里
        (泰冒山)-left->(数历山):西一百七十里
        (数历山)-left->(高山):西一百五十里
        (高山)-left->(女床山):西南三百里
        (女床山)-left->(龙首山):西二百里
        (龙首山)-left->(鹿台山):西二百里
        (鹿台山)-left->(鸟危山):西二百里
        (鸟危山)-left->(小次山):西四百里
        (小次山)-left->(大次山):西三百里
        (大次山)-left->(薰吴山):西四百里
        (薰吴山)-left->(厎阳山):西四百里
        (厎阳山)-left->(众兽山):西二百五十里
        (众兽山)-left->(皇人山):西五百里
        (皇人山)-left->(中皇山):西三百里
        (中皇山)-left->(西皇山):西三百五十里
        (西皇山)-left->(莱山):西三百五十里
    }

    rectangle 西次三山 {
        (崇吾山)-left->(长沙山):西北三百里
        (长沙山)-left->(不周山):西北三百七十里
        (不周山)-left->(峚山):西北四百二十里
        (峚山)-left->(钟山):西北四百二十里
        (钟山)-left->(泰器山):西一百八十里
        (泰器山)-left->(槐江山):西三百二十里
        (槐江山)-left->(昆仑山):西四百里
        (昆仑山)-left->(乐游山):西三百七十里
        (乐游山)-left->(蠃母山):西水行四百里，流沙二百里
        (蠃母山)-left->(玉山):西三百五十里
        (玉山)-left->(轩辕丘):西四百八十里
        (轩辕丘)-left->(积石山):西三百里
        (积石山)-left->(长留山):西二百里
        (长留山)-left->(章莪山):西二百八十里
        (章莪山)-left->(阴山):西三百里
        (阴山)-left->(符惕山):西二百里
        (符惕山)-left->(三危山):西二百二十里
        (三危山)-left->(槐山):西一百九十里
        (槐山)-left->(天山):西三百五十里
        (天山)-left->(泑山):西二百九十里
        (泑山)-left->(翼望山):西水行百里
    }

    rectangle 西次四山 {
        (阴山)-up->(劳山):北五十里
        (劳山)-left->(罢谷山):西五十里
        (罢谷山)-up->(申山):北一百七十里
        (申山)-up->(鸟山):北二百里
        (鸟山)-up->(上申山):北一百二十里
        (上申山)-up->(诸次山):北一百八十里
        (诸次山)-up->(号山):北一百八十里
        (号山)-up->(盂山):北二百二十里
        (盂山)-left->(白於山):西二百五十里
        (白於山)-left->(申首山):西北三百里
        (申首山)-left->(泾谷山):西五十五里
        (泾谷山)-left->(刚山):西一百二十里
        (刚山)-left->(刚山的尾端):西二百里
        (刚山的尾端)-left->(英鞮山):西三百五十里
        (英鞮山)-left->(曲山):西三百里
        (曲山)-left->(邽山):西二百六十里
        (邽山)-left->(鸟鼠同穴山):西二百二十里
        (鸟鼠同穴山)-left->(崦嵫山):西南三百六十里
    }

    (西山华山)-down->(西次二山)
    (西次二山)-down->(西次三山)
    (西次三山)-down->(西次四山)
}

rectangle 南山经 {
    rectangle 南山之首䧿山 {
        (招摇山)-right->(堂庭山):东三百里
        (堂庭山)-right->(猨翼山):东三百八十里
        (猨翼山)-right->(杻阳山):东三百七十里
        (杻阳山)-right->(柢山):东三百里
        (柢山)-right->(亶爰山):东四百里
        (亶爰山)-right->(基山):东三百里
        (基山)-right->(青丘山):东三百里
        (青丘山)-right->(箕尾山):东三百五十里
    }

    rectangle 南次二山 {
        (柜山)-right->(长右山):东南四百五十里
        (长右山)-right->(尧光山):东三百四十里
        (尧光山)-right->(羽山):东三百五十里
        (羽山)-right->(瞿父山):东三百七十里
        (瞿父山)-right->(句余山):东四百里
        (句余山)-right->(浮玉山):东五百里
        (浮玉山)-right->(成山):东五百里
        (成山)-right->(会稽山):东五百里
        (会稽山)-right->(夷山):东五百里
        (夷山)-right->(仆勾山):东五百里
        (仆勾山)-right->(咸阴山):东五百里
        (咸阴山)-right->(洵山):东四百里
        (洵山)-right->(虖勺山):东四百里
        (虖勺山)-right->(区吴山):东五百里
        (区吴山)-right->(鹿吴山):东五百里
        (鹿吴山)-right->(漆吴山):东五百里
    }

    rectangle 南次三山 {
        (天虞山)-right->(祷过山):东五百里
        (祷过山)-right->(发爽山):东五百里
        (发爽山)-right->(旄山):东四百里
        (旄山)-right->(非山):东四百里
        (非山)-right->(阳夹山):东五百里
        (阳夹山)-right->(灌湘山):东五百里
        (灌湘山)-right->(鸡山):东五百里
        (鸡山)-right->(令丘山):东四百里
        (令丘山)-right->(仑者山):东三百七十里
        (仑者山)-right->(禺槀山):东五百八十里
        (禺槀山)-right->(南禺山):东五百八十里
    }

    (南山之首䧿山)-down->(南次二山)
    (南次二山)-down->(南次三山)
}

(中山经)-up->(北山经)
(中山经)-right->(东山经)
(中山经)-down->(南山经)
(中山经)-left->(西山经)

(南山经)-down->(海外南经)
(海外南经)-down->(海内南经)
(海内南经)-down->(大荒南经)

(西山经)-left->(海外西经)
(海外西经)-left->(海内西经)
(海内西经)-left->(大荒西经)

(北山经)-up->(海外北经)
(海外北经)-up->(海内北经)
(海内北经)-up->(大荒北经)

(东山经)-right->(海外东经)
(海外东经)-right->(海内东经)
(海内东经)-right->(大荒东经)

footer 版本：0.1，日期：2024/10/18

@enduml