@startuml

title "山海经-山经-第二层"

skinparam packageStyle rectangle

rectangle 中山经 {
    (中山薄山)-down->(中次二山济山)
    (中次二山济山)-down->(中次三山负山)
    (中次三山负山)-down->(中次四山厘山)
    (中次四山厘山)-down->(中次五山薄山)
    (中次五山薄山)-down->(中次六山缟羝山)
    (中次六山缟羝山)-down->(中次七山苦山)
    (中次七山苦山)-down->(中次八山荆山)
    (中次八山荆山)-down->(中次九山岷山)
    (中次九山岷山)-down->(中次十山)
    (中次十山)-down->(中次一十一山荆山)
    (中次一十一山荆山)-down->(中次十二山洞庭山)
}

rectangle 东山经 {
    (东山之首)-right->(东次二山)
    (东次二山)-right->(东次三山)
    (东次三山)-right->(东次四山)
}

rectangle 北山经 {
    (北山之首)-up->(北次二山)
    (北次二山)-up->(北次三山)
}

rectangle 西山经 {
    (西山华山)-left->(西次二山)
    (西次二山)-left->(西次三山)
    (西次三山)-left->(西次四山)
}

rectangle 南山经 {
    (南山之首䧿山)-down->(南次二山)
    (南次二山)-down->(南次三山)
}

(中山经)-up->(北山经)
(中山经)-right->(东山经)
(中山经)-down->(南山经)
(中山经)-left->(西山经)

(南山经)-down->(海外南经)
(海外南经)-down->(海内南经)
(海内南经)-down->(大荒南经)

(西山经)-left->(海外西经)
(海外西经)-left->(海内西经)
(海内西经)-left->(大荒西经)

(北山经)-up->(海外北经)
(海外北经)-up->(海内北经)
(海内北经)-up->(大荒北经)

(东山经)-right->(海外东经)
(海外东经)-right->(海内东经)
(海内东经)-right->(大荒东经)

footer 版本：0.1，日期：2024/10/18

@enduml