@startuml

title "山海经-山经-第三层(全)"

left to right direction

skinparam packageStyle rectangle

rectangle 中山经 {
    rectangle 中山之首薄山 {
        (甘枣山)-right->(历儿山):东二十里
        (历儿山)-right->(渠猪山):东十五里
        (渠猪山)-right->(葱聋山):东三十五里
        (葱聋山)-right->(涹山):东十五里
        (涹山)-right->(脱扈山):东七十里
        (脱扈山)-right->(金星山):东二十里
        (金星山)-right->(泰威山):东七十里
        (泰威山)-right->(橿谷山):东十五里
        (橿谷山)-right->(吴林山):东百二十里
        (吴林山)-up->(牛首山):北三十里
        (牛首山)-up->(霍山):北四十里
        (霍山)-up->(合谷山):北五十二里
        (合谷山)-up->(阴山):北三十五里
        (阴山)-right->(鼓镫山):东北四百里
    }

    rectangle 中次二山济山 {
        (辉诸山)-down->(发视山):西南二百里
        (发视山)-left->(豪山):西三百里
        (豪山)-left->(鲜山):西三百里
        (鲜山)-left->(阳山):西三百里
        (阳山)-left->(昆吾山):西二百里
        (昆吾山)-left->(葌山):西百二十里
        (葌山)-left->(独苏山):西一百五十里
        (独苏山)-left->(蔓渠山):西二百里
    }

    rectangle 中次三山负山 {
        (敖岸山)-right->(青要山):东十里
        (青要山)-right->(槐山):东十里
        (槐山)-right->(宜苏山):东四十里
        (宜苏山)-right->(和山):东二十里
    }

    rectangle 中次四山厘山 {
        (鹿蹄山)-left->(扶猪山):西五十里
        (扶猪山)-left->(厘山):西一百二十里
        (厘山)-left->(箕尾山):西二百里
        (箕尾山)-left->(柄山):西二百五十里
        (柄山)-left->(白边山):西二百里
        (白边山)-left->(熊耳山):西二百里
        (熊耳山)-left->(牡山):西三百里
        (牡山)-left->(罐举山):西三百五十里
        (罐举山)-left->(玄扈山):夹着一条洛水
    }

    rectangle 中次五山薄山 {
        (苟林山)-right->(首山):东三百里
        (首山)-right->(属斤山):东三百里
        (属斤山)-right->(葱聋山):东三百里
        (葱聋山)-up->(条谷山):东北五百里
        (条谷山)-up->(超山):北十里
        (超山)-right->(成侯山):东五百里
        (成侯山)-right->(朝歌山):东五百里
        (朝歌山)-right->(槐山):东五百里
        (槐山)-right->(历山):东十里
        (历山)-right->(尸山):东十里
        (尸山)-right->(良余山):东十里
        (良余山)-down->(蛊尾山):东南十里
        (蛊尾山)-up->(升山):东北二十里
        (升山)-right->(阳虚山):东十二里
    }

    rectangle 中次六山缟羝山 {
        (平逢山)-left->(缟羝山):西十里
        (缟羝山)-left->(廆山):西十里
        (廆山)-left->(瞻诸山):西三十里
        (瞻诸山)-left->(娄涿山):西三十里
        (娄涿山)-left->(白石山):西四十里
        (白石山)-left->(谷山):西五十里
        (谷山)-left->(密山):西七十二里
        (密山)-left->(长石山):西百里
        (长石山)-left->(傅山):西一百四十里
        (傅山)-left->(橐山):西五十里
        (橐山)-left->(常烝山):西九十里
        (常烝山)-left->(夸父山):西九十里
        (夸父山)-left->(阳华山):西九十里
    }

    rectangle 中次七山苦山 {
        (休与山)-right->(鼓钟山):东三百里
        (鼓钟山)-right->(姑媱山):东二百里
        (姑媱山)-right->(苦山):东二十里
        (苦山)-right->(堵山):东二十七里
        (堵山)-right->(放皋山):东五十二里
        (放皋山)-right->(大苦山):东五十七里
        (大苦山)-right->(半石山):东七十里
        (半石山)-right->(少室山):东五十里
        (少室山)-right->(泰室山):东三十里
        (泰室山)-up->(讲山):北三十里
        (讲山)-up->(婴梁山):北三十里
        (婴梁山)-right->(浮戏山):东三十里
        (浮戏山)-right->(少陉山):东四十里
        (少陉山)-down->(太山):东南十里
        (太山)-right->(末山):东二十里
        (末山)-right->(役山):东二十五里
        (役山)-right->(敏山):东三十五里
        (敏山)-right->(大騩山):东三十里
    }

    rectangle 中次八山荆山 {
        (景山)-up->(荆山):东北百里
        (荆山)-up->(骄山):东北百五十里
        (骄山)-up->(女几山):东北一百五十里
        (女几山)-up->(宜诸山):东北二百里
        (宜诸山)-up->(纶山):东北三百五十里
        (纶山)-right->(陆危山):东二百里
        (陆危山)-right->(光山):东百三十里
        (光山)-right->(岐山):东百五十里
        (岐山)-right->(铜山):东百三十里
        (铜山)-up->(美山):东北一百里
        (美山)-up->(大尧山):东北百里
        (大尧山)-up->(灵山):东北三百里
        (灵山)-up->(龙山):东北七十里
        (龙山)-down->(衡山):东南五十里
        (衡山)-down->(石山):东南七十里
        (石山)-down->(若山):南百二十里
        (若山)-down->(玉山):东南一百二十里
        (玉山)-down->(灌山):东南七十里
        (灌山)-up->(仁举山):东北百五十里
        (仁举山)-right->(师每山):东五十里
        (师每山)-down->(琴鼓山):东南二百里
    }

    rectangle 中次九山岷山 {
        (女几山)-up->(岷山):东北三百里
        (岷山)-up->(崃山):东北一百四十里
        (崃山)-right->(崌山):东一百五十里
        (崌山)-right->(高梁山):东三百里
        (高梁山)-right->(蛇山):东四百里
        (蛇山)-right->(鬲山):东五百里
        (鬲山)-up->(隅阳山):东北三百里
        (隅阳山)-right->(岐山):东二百五十里
        (岐山)-right->(勾尔山):东三百里
        (勾尔山)-right->(风雨山):东一百五十里
        (风雨山)-up->(玉山):东北二百里
        (玉山)-right->(熊山):东一百五十里
        (熊山)-right->(槐山):东一百四十里
        (槐山)-right->(葛山):东二百里
        (葛山)-right->(贾超山):东一百七十里
    }

    rectangle 中次十山 {
        (首阳山)-left->(虎尾山):西五十里
        (虎尾山)-down->(繁缋山):西南五十里
        (繁缋山)-down->(勇石山):西南二十里
        (勇石山)-left->(复州山):西二十里
        (复州山)-left->(楮山):西三十里
        (楮山)-left->(又原山):西二十里
        (又原山)-left->(涿山):西五十里
        (涿山)-left->(丙山):西七十里
    }

    rectangle 中次一十一山荆山 {
        (翼望山)-up->(朝歌山):东北一百五十里
        (朝歌山)-down->(帝囷山):东南二百里
        (帝囷山)-down->(视山):东南五十里
        (视山)-down->(前山):东南二百里
        (前山)-down->(丰山):东南三百里
        (丰山)-up->(兔床山):东北八百里
        (兔床山)-right->(皮山):东六十里
        (皮山)-right->(瑶碧山):东六十里
        (瑶碧山)-right->(攻离山):东四十里
        (攻离山)-up->(袟周山):东北五十里
        (袟周山)-up->(堇理山):西北一百里
        (堇理山)-down->(依轱山):东南三十里
        (依轱山)-down->(即谷山):东南三十五里
        (即谷山)-down->(鸡山):东南四十里
        (鸡山)-down->(高前山):东南五十里
        (高前山)-down->(游戏山):东南三十里
        (游戏山)-down->(从山):东南三十五里
        (从山)-down->(婴䃌山):东南三十里
        (婴䃌山)-down->(毕山):东南三十里
        (毕山)-down->(乐马山):东南二十里
        (乐马山)-down->(葴山):东南二十五里
        (葴山)-right->(婴山):东四十里
        (婴山)-right->(虎首山):东三十里
        (虎首山)-right->(婴侯山):东二十里
        (婴侯山)-right->(大孰山):东五十里
        (大孰山)-right->(卑山):东四十里
        (卑山)-right->(倚帝山):东三十里
        (倚帝山)-right->(鲵山):东三十里
        (鲵山)-right->(雅山):东三十里
        (雅山)-right->(宣山):东五十五里
        (宣山)-right->(衡山):东四十五里
        (衡山)-right->(丰山):东四十里
        (丰山)-right->(妪山):东七十里
        (妪山)-right->(鲜山):东三十里
        (鲜山)-right->(皋山):东三十里
        (皋山)-right->(大支山):东二十五里
        (大支山)-right->(区吴山):东五十里
        (区吴山)-right->(声匈山):东五十里
        (声匈山)-right->(大騩山):东五十里
        (大騩山)-right->(踵臼山):东十里
        (踵臼山)-up->(历石山):东北七十里
        (历石山)-down->(求山):东南一百里
        (求山)-right->(丑阳山):东二百里
        (丑阳山)-right->(奥山):东三百里
        (奥山)-right->(服山):东三十五里
        (服山)-right->(杳山):东三百里
        (杳山)-right->(几山):东三百五十里
    }

    rectangle 中次十二山洞庭山 {
        (篇遇山)-down->(云山):东南五十里
        (云山)-down->(龟山):东南一百三十里
        (龟山)-right->(丙山):东七十里
        (丙山)-down->(风伯山):东南五十里
        (风伯山)-right->(夫夫山):东一百五十里
        (夫夫山)-down->(洞庭山):东南一百二十里
        (洞庭山)-down->(暴山):东南一百八十里
        (暴山)-down->(即公山):东南二百里
        (即公山)-down->(尧山):东南一百五十九里
        (尧山)-down->(江浮山):东南一百里
        (江浮山)-right->(真陵山):东二百里
        (真陵山)-down->(阳帝山):东南一百二十里
        (阳帝山)-down->(柴桑山):南九十里
        (柴桑山)-right->(荣余山):东二百三十里
    }

    (中山之首薄山)-down->(中次二山济山)
    (中次二山济山)-down->(中次三山负山)
    (中次三山负山)-down->(中次四山厘山)
    (中次四山厘山)-down->(中次五山薄山)
    (中次五山薄山)-down->(中次六山缟羝山)
    (中次六山缟羝山)-down->(中次七山苦山)
    (中次七山苦山)-down->(中次八山荆山)
    (中次八山荆山)-down->(中次九山岷山)
    (中次九山岷山)-down->(中次十山)
    (中次十山)-down->(中次一十一山荆山)
    (中次一十一山荆山)-down->(中次十二山洞庭山)
}

rectangle 东山经 {
    rectangle 东山之首 {
        (樕朱虫山)-down->(藟山):南三百里
        (藟山)-down->(栒状山):南三百里
        (栒状山)-down->(勃亝山):南三百里
        (勃亝山)-down->(番条山):南三百里
        (番条山)-down->(姑儿山):南四百里
        (姑儿山)-down->(高氏山):南四百里
        (高氏山)-down->(岳山):南三百里
        (岳山)-down->(犲山):南三百里
        (犲山)-down->(独山):南三百里
        (独山)-down->(东岳泰山):南三百里
        (东岳泰山)-down->(竹山):南三百里
    }

    rectangle 东次二山 {
        (空桑山)-down->(曹夕山):南六百里
        (曹夕山)-left->(峄皋山):西南四百里
        (峄皋山)-down->(葛山之尾):南水行五百里，流沙三百里
        (葛山之尾)-down->(葛山之首):南三百八十里
        (葛山之首)-down->(余峨山):南三百八十里
        (余峨山)-down->(杜父山):南三百里
        (杜父山)-down->(耿山):南三百里
        (耿山)-down->(卢其山):南三百里
        (卢其山)-down->(姑射山):南三百八十里
        (姑射山)-down->(北姑射山):南水行三百里，流沙百里
        (北姑射山)-down->(南姑射山):南三百里
        (南姑射山)-down->(碧山):南三百里
        (碧山)-down->(缑氏山):南五百里
        (缑氏山)-down->(姑逢山):南三百里
        (姑逢山)-down->(凫丽山):南五百里
        (凫丽山)-down->(䃌山):南五百里
    }

    rectangle 东次三山 {
        (尸胡山)-down->(岐山):南水行八百里
        (岐山)-down->(诸钩山):南水行五百里
        (诸钩山)-down->(中父山):南水行七百里
        (中父山)-right->(胡射山):东水行千里
        (胡射山)-down->(孟子山):南水行七百里
        (孟子山)-down->(跂踵山):南水行五百里，流沙五百里
        (跂踵山)-down->(踇隅山):南水行九百里
        (踇隅山)-down->(无皋山):南水行五百里，流沙三百里
    }

    rectangle 东次四山 {
        (北号山)-down->(旄山):南三百里
        (旄山)-down->(东始山):南三百二十里
        (东始山)-right->(女烝山):东南三百里
        (女烝山)-right->(钦山):东南二百里
        (钦山)-right->(子桐山):东南二百里
        (子桐山)-right->(剡山):东北二百里
        (剡山)-right->(太山):东二百里
    }

    (东山之首)-right->(东次二山)
    (东次二山)-right->(东次三山)
    (东次三山)-right->(东次四山)
}

rectangle 北山经 {
    rectangle 北山之首 {
        (单狐山)-up->(求如山):北二百五十里
        (求如山)-up->(带山):北三百里
        (带山)-up->(谯明山):北四百里
        (谯明山)-up->(涿光山):北三百五十里
        (涿光山)-up->(虢山):北三百八十里
        (虢山)-up->(虢山之尾):北四百里
        (虢山之尾)-up->(丹熏山):北二百里
        (丹熏山)-up->(石者山):北二百八十里
        (石者山)-up->(边春山):北百一十里
        (边春山)-up->(蔓联山):北二百里
        (蔓联山)-up->(单张山):北百八十里
        (单张山)-up->(灌题山):北三百二十里
        (灌题山)-up->(潘侯山):北二百里
        (潘侯山)-up->(小咸山):北二百三十里
        (小咸山)-up->(大咸山):北二百八十里
        (大咸山)-up->(敦薨山):北三百二十里
        (敦薨山)-up->(少咸山):北二百里
        (少咸山)-up->(狱法山):北二百里
        (狱法山)-up->(北岳山):北二百里
        (北岳山)-up->(浑夕山):北百八十里
        (浑夕山)-up->(北单山):北五十里
        (北单山)-up->(罴差山):北百里
        (罴差山)-up->(北鲜山):北百八十里
        (北鲜山)-up->(隄山):北百七十里
    }

    rectangle 北次二山 {
        (管涔山)-up->(少阳山):北二百五十里
        (少阳山)-up->(县雍山):北五十里
        (县雍山)-up->(狐岐山):北二百里
        (狐岐山)-up->(白沙山):北三百五十里
        (白沙山)-up->(尔是山):北四百里
        (尔是山)-up->(狂山):北三百八十里
        (狂山)-up->(诸余山):北三百八十里
        (诸余山)-up->(敦头山):北三百五十里
        (敦头山)-up->(钩吾山):北三百五十里
        (钩吾山)-up->(北嚣山):北三百里
        (北嚣山)-up->(梁渠山):北三百五十里
        (梁渠山)-up->(姑灌山):北四百里
        (姑灌山)-up->(湖灌山):北三百八十里
        (湖灌山)-up->(洹山):北水行五百里，流沙三百里
        (洹山)-up->(敦题山):北三百里
    }

    rectangle 北次三山 {
        (北次三山之首-太行山-归山)-up->(龙侯山):东北二百里
        (龙侯山)-up->(马成山):东北二百里
        (马成山)-up->(咸山):东北七十里
        (咸山)-up->(天池山):东北二百里
        (天池山)-right->(阳山):东三百里
        (阳山)-right->(贲闻山):东三百五十里
        (贲闻山)-up->(王屋山):北百里
        (王屋山)-up->(教山):东北三百里
        (教山)-down->(景山):南三百里
        (景山)-down->(孟门山):东南三百二十里
        (孟门山)-down->(平山):东南三百二十里
        (平山)-right->(京山):东二百里
        (京山)-right->(虫尾山):东二百里
        (虫尾山)-right->(彭比山):东三百里
        (彭比山)-right->(小侯山):东百八十里
        (小侯山)-up->(泰头山):东三百七十里
        (泰头山)-up->(轩辕山):东北二百里
        (轩辕山)-up->(谒戾山):北二百里
        (谒戾山)-right->(沮洳山):东三百里
        (沮洳山)-up->(神囷山):北三百里
        (神囷山)-up->(发鸠山):北二百里
        (发鸠山)-up->(少山):东北百二十里
        (少山)-up->(锡山):东北二百里
        (锡山)-up->(景山):北二百里
        (景山)-up->(题首山):北百里
        (题首山)-up->(绣山):北百里
        (绣山)-up->(松山):北百二十里
        (松山)-up->(敦与山):北百二十里
        (敦与山)-up->(柘山):北百七十里
        (柘山)-up->(维龙山):北三百里
        (维龙山)-up->(白马山):北百八十里
        (白马山)-up->(空桑山):北二百里
        (空桑山)-up->(泰戏山):北三百里
        (泰戏山)-up->(石山):北三百里
        (石山)-up->(童戎山):北二百里
        (童戎山)-up->(高是山):北三百里
        (高是山)-up->(陆山):北三百里
        (陆山)-up->(沂山):北二百里
        (沂山)-up->(燕山):北百二十里
        (燕山)-up->(饶山):北山行五百里，水行五百里
        (饶山)-up->(乾山):北四百里
        (乾山)-up->(伦山):北五百里
        (伦山)-up->(碣石山):北五百里
        (碣石山)-up->(雁门山):北水行五百里
        (雁门山)-up->(帝都山):北水行四百里
        (帝都山)-up->(錞于毋逢山):北五百里
    }

    (北山之首)-left->(北次二山)
    (北次二山)-left->(北次三山)
}

rectangle 西山经 {
    rectangle 西山华山 {
        (钱来山)-left->(松果山):西四十五里
        (松果山)-left->(太华山):西六十里
        (太华山)-left->(小华山):西八十里
        (小华山)-left->(符禺山):西八十里
        (符禺山)-left->(石脆山):西六十里
        (石脆山)-left->(英山):西七十里
        (英山)-left->(竹山):西五十二里
        (竹山)-left->(浮山):西一百二十里
        (浮山)-left->(羭次山):西七十里
        (羭次山)-left->(时山):西一百五十里
        (时山)-left->(南山):西一百七十里
        (南山)-left->(大时山):西一百八十里
        (大时山)-left->(嶓冢山):西三百二十里
        (嶓冢山)-left->(天帝山):西三百五十里
        (天帝山)-left->(皋涂山):西南三百八十里
        (皋涂山)-left->(黄山):西一百八十里
        (黄山)-left->(翠山):西二百里
        (翠山)-left->(螝山):西二百五十里
    }

    rectangle 西次二山 {
        (铃山)-left->(泰冒山):西二百里
        (泰冒山)-left->(数历山):西一百七十里
        (数历山)-left->(高山):西一百五十里
        (高山)-left->(女床山):西南三百里
        (女床山)-left->(龙首山):西二百里
        (龙首山)-left->(鹿台山):西二百里
        (鹿台山)-left->(鸟危山):西二百里
        (鸟危山)-left->(小次山):西四百里
        (小次山)-left->(大次山):西三百里
        (大次山)-left->(薰吴山):西四百里
        (薰吴山)-left->(厎阳山):西四百里
        (厎阳山)-left->(众兽山):西二百五十里
        (众兽山)-left->(皇人山):西五百里
        (皇人山)-left->(中皇山):西三百里
        (中皇山)-left->(西皇山):西三百五十里
        (西皇山)-left->(莱山):西三百五十里
    }

    rectangle 西次三山 {
        (崇吾山)-left->(长沙山):西北三百里
        (长沙山)-left->(不周山):西北三百七十里
        (不周山)-left->(峚山):西北四百二十里
        (峚山)-left->(钟山):西北四百二十里
        (钟山)-left->(泰器山):西一百八十里
        (泰器山)-left->(槐江山):西三百二十里
        (槐江山)-left->(昆仑山):西四百里
        (昆仑山)-left->(乐游山):西三百七十里
        (乐游山)-left->(蠃母山):西水行四百里，流沙二百里
        (蠃母山)-left->(玉山):西三百五十里
        (玉山)-left->(轩辕丘):西四百八十里
        (轩辕丘)-left->(积石山):西三百里
        (积石山)-left->(长留山):西二百里
        (长留山)-left->(章莪山):西二百八十里
        (章莪山)-left->(阴山):西三百里
        (阴山)-left->(符惕山):西二百里
        (符惕山)-left->(三危山):西二百二十里
        (三危山)-left->(槐山):西一百九十里
        (槐山)-left->(天山):西三百五十里
        (天山)-left->(泑山):西二百九十里
        (泑山)-left->(翼望山):西水行百里
    }

    rectangle 西次四山 {
        (阴山)-up->(劳山):北五十里
        (劳山)-left->(罢谷山):西五十里
        (罢谷山)-up->(申山):北一百七十里
        (申山)-up->(鸟山):北二百里
        (鸟山)-up->(上申山):北一百二十里
        (上申山)-up->(诸次山):北一百八十里
        (诸次山)-up->(号山):北一百八十里
        (号山)-up->(盂山):北二百二十里
        (盂山)-left->(白於山):西二百五十里
        (白於山)-left->(申首山):西北三百里
        (申首山)-left->(泾谷山):西五十五里
        (泾谷山)-left->(刚山):西一百二十里
        (刚山)-left->(刚山的尾端):西二百里
        (刚山的尾端)-left->(英鞮山):西三百五十里
        (英鞮山)-left->(曲山):西三百里
        (曲山)-left->(邽山):西二百六十里
        (邽山)-left->(鸟鼠同穴山):西二百二十里
        (鸟鼠同穴山)-left->(崦嵫山):西南三百六十里
    }

    (西山华山)-down->(西次二山)
    (西次二山)-down->(西次三山)
    (西次三山)-down->(西次四山)
}

rectangle 南山经 {
    rectangle 南山之首䧿山 {
        (招摇山)-right->(堂庭山):东三百里
        (堂庭山)-right->(猨翼山):东三百八十里
        (猨翼山)-right->(杻阳山):东三百七十里
        (杻阳山)-right->(柢山):东三百里
        (柢山)-right->(亶爰山):东四百里
        (亶爰山)-right->(基山):东三百里
        (基山)-right->(青丘山):东三百里
        (青丘山)-right->(箕尾山):东三百五十里
    }

    rectangle 南次二山 {
        (柜山)-right->(长右山):东南四百五十里
        (长右山)-right->(尧光山):东三百四十里
        (尧光山)-right->(羽山):东三百五十里
        (羽山)-right->(瞿父山):东三百七十里
        (瞿父山)-right->(句余山):东四百里
        (句余山)-right->(浮玉山):东五百里
        (浮玉山)-right->(成山):东五百里
        (成山)-right->(会稽山):东五百里
        (会稽山)-right->(夷山):东五百里
        (夷山)-right->(仆勾山):东五百里
        (仆勾山)-right->(咸阴山):东五百里
        (咸阴山)-right->(洵山):东四百里
        (洵山)-right->(虖勺山):东四百里
        (虖勺山)-right->(区吴山):东五百里
        (区吴山)-right->(鹿吴山):东五百里
        (鹿吴山)-right->(漆吴山):东五百里
    }

    rectangle 南次三山 {
        (天虞山)-right->(祷过山):东五百里
        (祷过山)-right->(发爽山):东五百里
        (发爽山)-right->(旄山):东四百里
        (旄山)-right->(非山):东四百里
        (非山)-right->(阳夹山):东五百里
        (阳夹山)-right->(灌湘山):东五百里
        (灌湘山)-right->(鸡山):东五百里
        (鸡山)-right->(令丘山):东四百里
        (令丘山)-right->(仑者山):东三百七十里
        (仑者山)-right->(禺槀山):东五百八十里
        (禺槀山)-right->(南禺山):东五百八十里
    }

    (南山之首䧿山)-down->(南次二山)
    (南次二山)-down->(南次三山)
}

(中山经)-up->(北山经)
(中山经)-right->(东山经)
(中山经)-down->(南山经)
(中山经)-left->(西山经)

(南山经)-down->(海外南经)
(海外南经)-down->(海内南经)
(海内南经)-down->(大荒南经)

(西山经)-left->(海外西经)
(海外西经)-left->(海内西经)
(海内西经)-left->(大荒西经)

(北山经)-up->(海外北经)
(海外北经)-up->(海内北经)
(海内北经)-up->(大荒北经)

(东山经)-right->(海外东经)
(海外东经)-right->(海内东经)
(海内东经)-right->(大荒东经)

footer 版本：0.2，日期：2024/10/19

@enduml